# Generated by Django 2.2.5 on 2019-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pelis'),
        ),
    ]
